### ISSUE TITLE
Issue Related to License

### ISSUE THREAD

**Issue by iamwatchdogs** [nishant-ai/DSA-Help#56]
# Issue Related to License

## Introduction:
Hi, There @nishant-ai, I would love to contribute to this Repo.
But this Repo is missing one of the crucial files required for collaboration/contribution.
This Repo is missing the "**LICENSE**" file which provides licensing of the Repo allowing us to contribute to it legally.
It's also **Free**.

## Reference:
This is mentioned in the guide for contribution provided by GitHub itself. Once check it out down here,
[A checklist before you contribute](https://opensource.guide/how-to-contribute/#a-checklist-before-you-contribute)

## Solution:
- [ ] Create a file name "LICENSE".
- [ ] Copy the licensing content into it. ( You can select it from [choosealicense.com](https://choosealicense.com/), I would suggest [MIT License](https://choosealicense.com/licenses/mit/) )
- [ ] Save & Push the changes in the Repo.

---

### Note:
If you can do it by yourself then it is fine, or If you want me to deal with this you can just comment on this issue and I'll be working on it as soon as possible.

---

**Comment by nishant-ai** [comment]
Sure @iamwatchdogs! Please work on it and open a PR, i'll surely look into it!

**Comment by iamwatchdogs** [comment]
For sure, I'll work on it this evening. I'm currently in college.

**Comment by iamwatchdogs** [comment]
# Update on the issue

Hey @nishant-ai,
I am also adding a file named "CODE_OF_CONDUCT.md" as it is suggested by the open-source guide on GitHub.

## Reference : 
- [Anatomy of an open source project](https://opensource.guide/how-to-contribute/#anatomy-of-an-open-source-project).
- [Establishing a code of conduct](https://opensource.guide/code-of-conduct/).
- [A Code of Conduct for Open Source Communities](https://www.contributor-covenant.org/).

## Info about file present in PR:
- The "CODE_OF_CONDUCT.md" contains one of the standard code-of-conduct which is [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md).
- And about the LICENSE, I have chosen the [MIT LICENSE](https://choosealicense.com/licenses/mit/).

**Comment by iamwatchdogs** [comment]
Hey @nishant-ai,
Check out PR #80 I have sent, this will resolve this issue.
