### ISSUE TITLE
Required Common File fixes

### ISSUE THREAD

**Issue by iamwatchdogs** [nishant-ai/DSA-Help#89]
## Introduction
Hey, it's me again @nishant-ai.
After adding up the license and code of conduct, I was getting ready to contribute to the original technical content.
But, As I browse through the Repo, I have found the following common issues (despite the programming language chosen).

- [ ] Missing extension
- [ ] Invalid Class name
- [ ] README.md required updation.

> These issues might raise the problem of not being complied and with insufficient information to understand and make good of this repo

## Solution
I'm ready to work on these issues, can you assign me to resolve these issues?

**Comment by nishant-ai** [comment]
Sure @iamwatchdogs! You can work on it!

**Comment by iamwatchdogs** [comment]
Thank you or Assigning me for the Job, I'm gonna finish it ASAP

**Comment by iamwatchdogs** [comment]
Hey there @nishant-ai,
I got my job done, you can check my work on PR #114.
